### PR TITLE
Prepare for v1.0.0 release

### PR DESCRIPTION
**Pull request by lopopolo**
# Release Notes

Release 1.0.0 of strftime-ruby.

[`strftime-ruby` is available on crates.io](https://crates.io/crates/strftime-ruby/1.0.0).

`strftime-ruby` is a Ruby 3.1.2 compatible implementation of the [`Time#strftime`] method. The `strftime` routines provided by this crate are [POSIX-compatible], except for intentionally ignoring the `E` and `O` modified conversion specifiers.

[`Time#strftime`]: https://ruby-doc.org/core-3.1.2/Time.html#method-i-strftime
[POSIX-compatible]: https://pubs.opengroup.org/onlinepubs/9699919799/functions/strftime.html

## API

There are 5 `strftime` functions in this crate which vary in the type of format specifier they take and how they write the formatted output:

- `strftime::buffered::strftime`: Takes a `&[u8]` format specifier and writes to the provided byte slice.
- `strftime::fmt::strftime`: Takes a `&str` format specifier and writes to the provided `core::fmt::Write` object.
- `strftime::bytes::strftime`: Takes a `&[u8]` format specifier and writes to a newly allocated `Vec`, which is returned.
- `strftime::string::strftime`: Takes a `&str` format specifier and writes to a newly allocated `String`, which is returned.
- `strftime::io::strftime`: Takes a `&[u8]` format specifier and writes to the provided `std::io::Write` object.

## Allocations

The only routines that allocate in this crate are `strftime::bytes::strftime` and `strftime::string::strftime`. These routines use fallible allocation APIs from `alloc` and return errors to callers.

`strftime::fmt::strftime` and `strftime::io::strftime` perform no allocations on their own, but the provided writers may allocate.

## Cargo Features

`strftime-ruby` has **alloc** and **std** features. All features are enabled by default.

`strftime::buffered::strftime` and `strftime::fmt::strftime` are available when this crate is compiled without any features and are usable in a `no_std` context.

The **alloc** feature enables `strftime::bytes::strftime` and `strftime::string::strftime`.

The **std** feature enables `strftime::io::strftime`.

## Test Coverage

`strftime-ruby` has 100% line coverage, which is enforced by CI, and is fuzzed regularly.

### CODE REVIEW

**Comment by lopopolo** [comment]
Will wait for https://github.com/artichoke/strftime-ruby/pull/55 to be merged and will rebase.

**Comment by lopopolo** [comment]
READMEs looks good. Only broken link is the `docs.rs` link, which will be fixed when we release: https://github.com/artichoke/strftime-ruby/pull/59.

**Comment by lopopolo** [comment]
@x-hgg-x what do you think of these release notes? Do you think they could double as the announcement text?

**Comment by lopopolo** [comment]
blocked on resolving all outstanding PRs.

**Comment by x-hgg-x** [comment]
> @x-hgg-x what do you think of these release notes? Do you think they could double as the announcement text?

Yes it is a good summary of the crate capabilities.

**Review by x-hgg-x — APPROVED** [review]

**Pull request merged**
