### PR TITLE
Add code coverage workflow which uploads to S3

### LINKED ISSUE #21: Add code coverage tests
I think we might be able to reuse some of the same harness from `rust-asn1`: https://github.com/alex/rust-asn1/blob/afe141f6df60dee51fd5d78884361beaa46a8122/.github/workflows/ci.yml#L101-L170

Having 100% coverage seems like a good goal to strive for given the complexity of the parsing.

### PR DESCRIPTION
**Pull request by lopopolo**
Closes https://github.com/artichoke/strftime-ruby/issues/21.

### CODE REVIEW

**Comment by lopopolo** [comment]
huzzah! https://codecov.artichokeruby.org/strftime-ruby/index.html

**Comment by lopopolo** [comment]
@x-hgg-x this uses your script from https://github.com/artichoke/strftime-ruby/issues/21#issuecomment-1216896809.

Coverage is published here: https://codecov.artichokeruby.org/strftime-ruby/index.html.

I put the workflow together to get the AWS bits sorted out. If we want to post coverage results and diffs back to the PR, we can iterate further.

Merging for now.

**Comment by x-hgg-x** [comment]
Nice! Before uploading the html files with `aws s3 cp`, should we delete the previous files in the folder, since we may add or remove source files ?

**Comment by lopopolo** [comment]
We can use `aws s3 sync --delete` but I'd have to add delete object permissions. Currently the STS token has put object permissions only.

**Comment by lopopolo** [comment]
Tracking the additional permissions here:

- https://github.com/artichoke/project-infrastructure/issues/334

**Pull request merged**
