### PR TITLE
Add better README descriptions of what each cargo feature activates

### PR DESCRIPTION
**Pull request by lopopolo**

### CODE REVIEW

**Comment by lopopolo** [comment]
@x-hgg-x I added this to the release notes and I think it makes for a better opening paragraph in the README. What do you think? Would you like me to include this change in this PR?

> `strftime-ruby` is a Ruby 3.1.2 compatible implementation of the [`Time#strftime`](https://ruby-doc.org/core-3.1.2/Time.html#method-i-strftime) method. The `strftime` routines provided by this crate are [POSIX-compatible](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strftime.html), except for intentionally ignoring the `E` and `O` modified conversion specifiers.

**Comment by x-hgg-x** [comment]
Yes it is better than what we have now.

**Review by x-hgg-x — APPROVED** [review]

**Comment by lopopolo** [comment]
Awesome. I'll add this in the morning. After this lands, I'm comfortable with releasing this to crates.io. Are you?

If yes, I'll do the release tomorrow.

**Comment by x-hgg-x** [comment]
Yes, we can release after merging this.

**Pull request merged**
